[tool.ruff]
line-length = 100


[tool.ruff.lint]
select = ["E","F","B","S"]
ignore = []

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["S101"]

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-q"
